from pathlib import Path

APP_NAME = "aws-cli-tools"
VERSION = "0.9.0"

AWS_DOT_AWS_DIR = Path.home() / ".aws"
AWS_CREDENTIALS_FILE = AWS_DOT_AWS_DIR / "credentials"
AWS_CONFIG_FILE = AWS_DOT_AWS_DIR / "config"

DEFAULT_PROFILE = "default"
DEFAULT_STS_REGION = "ap-northeast-2"

CACHE_DIR = Path.home() / ".cache" / APP_NAME
RESOLVE_CACHE_FILE = CACHE_DIR / "resolve-instance.json"
REGION_FAILURE_CACHE_FILE = CACHE_DIR / "region-failures.json"
SSM_TARGETS_CACHE_FILE = CACHE_DIR / "ssm-targets.json"
EC2_INVENTORY_OUTPUT_DIR = Path.home() / "Downloads" / APP_NAME / "ec2-inventory"
RI_INVENTORY_OUTPUT_DIR = Path.home() / "Downloads" / APP_NAME / "ri-inventory"
SAVINGS_PLAN_INVENTORY_OUTPUT_DIR = Path.home() / "Downloads" / APP_NAME / "sp-inventory"
COMMITMENT_INVENTORY_OUTPUT_DIR = Path.home() / "Downloads" / APP_NAME / "commitment-inventory"

SAVINGS_PLANS_API_REGION = "us-east-1"

INSTANCE_ID_CACHE_TTL_SECONDS = 300
IP_CACHE_TTL_SECONDS = 60
REGION_FAILURE_CACHE_TTL_SECONDS = 300
SSM_TARGETS_CACHE_TTL_SECONDS = 300

DEFAULT_CONNECT_TIMEOUT_SECONDS = 3
DEFAULT_READ_TIMEOUT_SECONDS = 5
DEFAULT_MAX_ATTEMPTS = 1

REGION_PRIORITY_ENV_VAR = "AWS_REGION_PRIORITY"
